kind = "web"
previewPath = "/"
title = "Angeliki- portfolio"
version = "1.0.0"
id = "artifacts/portfolio-v2"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22232

[services.development]
run = "pnpm --filter @workspace/portfolio-v2 run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/portfolio-v2", "run", "build" ]
publicDir = "artifacts/portfolio-v2/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22232"
BASE_PATH = "/"
