// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio-variants/BlockBento.tsx": () => import("../components/mockups/portfolio-variants/BlockBento.tsx"),
  "./components/mockups/portfolio-variants/BlockButtonTitles.tsx": () => import("../components/mockups/portfolio-variants/BlockButtonTitles.tsx"),
  "./components/mockups/portfolio-variants/BlockCompactExperience.tsx": () => import("../components/mockups/portfolio-variants/BlockCompactExperience.tsx"),
  "./components/mockups/portfolio-variants/BlockCompactH1.tsx": () => import("../components/mockups/portfolio-variants/BlockCompactH1.tsx"),
  "./components/mockups/portfolio-variants/BlockCompactH2.tsx": () => import("../components/mockups/portfolio-variants/BlockCompactH2.tsx"),
  "./components/mockups/portfolio-variants/BlockCompactH3.tsx": () => import("../components/mockups/portfolio-variants/BlockCompactH3.tsx"),
  "./components/mockups/portfolio-variants/BlockGrid.tsx": () => import("../components/mockups/portfolio-variants/BlockGrid.tsx"),
  "./components/mockups/portfolio-variants/BlockLogos.tsx": () => import("../components/mockups/portfolio-variants/BlockLogos.tsx"),
  "./components/mockups/portfolio-variants/Notion.tsx": () => import("../components/mockups/portfolio-variants/Notion.tsx"),
  "./components/mockups/portfolio-variants/OfferingVariant.tsx": () => import("../components/mockups/portfolio-variants/OfferingVariant.tsx"),
  "./components/mockups/portfolio-variants/Substack.tsx": () => import("../components/mockups/portfolio-variants/Substack.tsx"),
  "./components/mockups/portfolio-variants/Terminal.tsx": () => import("../components/mockups/portfolio-variants/Terminal.tsx"),
  "./components/mockups/portfolio-variants/VariantA.tsx": () => import("../components/mockups/portfolio-variants/VariantA.tsx"),
  "./components/mockups/portfolio-variants/VariantB.tsx": () => import("../components/mockups/portfolio-variants/VariantB.tsx"),
  "./components/mockups/portfolio-variants/VariantC.tsx": () => import("../components/mockups/portfolio-variants/VariantC.tsx")
};
